### ISSUE TITLE
Application crash 

### ISSUE THREAD

**Issue by Unsimpable2** [POLSL-SE/whaaale#24]
Steps how to reproduce bug: 
- Download [this](https://popo.jpl.nasa.gov/avcl/y06_data/f060426t01p00r07.tar.gz) file,
- Extract,
- Open this file "f060426t01p00r07c_ort_glt.hdr",
- Don't change bit per pixel, leave 13,
- Click "Fake Color",
- Application crashes.

Expected result:
- No application crash.

Actual result:
- Application crash.

Build of application and operating system on which was tested:
- 7601b07
- Win 10 Enterprise

Question
- Perhaps image is only single band and that why it's crashing application?

**Comment by krzysdz** [comment]
According to the `f060426t01p00r07c_geo.readme` file from the dataset, the file you tried to open is not a hyperspectral image, but a geometric look up table, which contains 2 *bands*:

> ```
> *.glt       GEOMETRIC LOOK UP TABLE
>
> 
> File type:  Binary
> 
> Contents:   Band 1 original sample number for the georectified image location.
>             Band 2 original line number for the georectified image location.
>             A negative value indicates the georectified value has been 
>             nearest neighbor interpolated
> 
> 
> ----------------------------------------------------------------------------
> 
> *.glt.hdr   HEADER FILE FOR THE GEOMETRIC LOOK UP TABLE
> 
> File type:  ASCII
> 
> Contents:   File format description for the *.glt file.
> ```

The description section in the header file suggests the same:

```ENVI
ENVI
description = {
AVIRIS geocoding look-up file, pixel size =       2.10000
```

8930a50c801fe528c604181ceaa97767cd4e7929 changes the crash to an error pop-up during the loading process
