### ISSUE TITLE
Magic wand doesn't work correctly

### ISSUE THREAD

**Issue by Unsimpable2** [POLSL-SE/whaaale#25]
Steps how to reproduce bug: 
- Download [this](https://popo.jpl.nasa.gov/avcl/y06_data/f060426t01p00r07.tar.gz) file,
- Extract,
- Open this file "f060426t01p00r07c_obs_ort.hdr",
- Choose "Global" or "Per band" option,
- Click "Fake color",
- Set three options to such value that image is visible,
- Click "Magic Wand",
- Click anywhere on image with color,
- Image is changed to white and it's back to "Single" band option.

Expected result:
- Should highlight only chosen color/band.

Actual result:
- Color is changed to white and application goes to "Single" tab.

Build of application and operating system on which was tested:
- 7601b07
- Win 10 Enterprise

**Comment by krzysdz** [comment]
While the file you've listed here doesn't contain radiance data, it looks like there is a real bug in the logic.

As for what the file contains, the description from `AVIRIS-ORTHO-PROCESSING.doc` says:
> In addition to the orthocorrection upgrade there is a wholly new data set (*_obs and *_obs_ort) that contains pertinent **parameters relating to the geometry of the observation and illumination conditions**.  The two versions of this file are before and after GLT-application.  The file \*_obs is in the raw spatial format and matches the uncorrected AVIRIS data.  The \*_obs_ort file has been rendered using the \*_ort_glt lookup table and matches the orthocorrected imagery.  This observation parameter file has ten bands.  The ten bands, in order, are: path length (sensor-to-ground in meters); to-sensor-azimuth (0 to 360 degrees cw from N); to-sensor-zenith (0 to 90 degrees from zenith); to-sun-azimuth; to-sun-zenith; phase (degrees between to-sensor and to-sun vectors in principal plane); slope (local surface slope as derived from DEM in degrees); aspect (local surface aspect 0 to 360 degrees cw from N); cosine i (apparent local illumination factor based on DEM slope and aspect and to-sun vector, -1 to 1) and UTC time (decimal hours for mid-line pixels).  We encourage anyone using these auxiliary parameters, especially for science-critical applications, to verify them against other models and sources as this is a new implementation and an experimental data set.
