### ISSUE TITLE
"C" shortcut doesn't work

### ISSUE THREAD

**Issue by Unsimpable2** [POLSL-SE/whaaale#26]
Steps how to reproduce bug:
- Open any .hrd file,
- Set value of mono or fake color band,
- Select point or area,
- Click on curve,
- Press "C" key.

Expected result:
- Application should export plot as .csv file. 

Actual result:
- No action. 

Build of application and operating system on which was tested:
- #1b8bd4b
- Win 10 Enterprise

**Comment by krzysdz** [comment]
`C` is different from `c` (which is a shortcut for back) and means `Shift+c`.
