### ISSUE TITLE
Prepare a basic main window

### ISSUE THREAD

**Issue by krzysdz** [POLSL-SE/whaaale#8]
Prepare a basic window layout with menu bar, buttons/settings and place for `ImagePreview` and `SpectralViewer` widgets.

The UI should be implemented in the `MainWindow` class derived from `QMainWindow`. For UI design details ask @balnurasabitovna.
Current UI project is available on [Figma](https://www.figma.com/file/iAxLzVdYS4r2uTiH4lwwY8/Interface1?node-id=0%3A1&t=ksK8NIEEbrMPmWpt-1).

**Comment by przebac659** [comment]
@balnurasabitovna what should be under menu/file, menu/view and menu/help?
For now in menu/file there is 'open' and 'exit'.
