### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by krzysdz** [POLSL-SE/whaaale#9]
Prepare `ImagePreview` class capable of displaying the image from a single (mono) band or 3 bands in RGB mode. This class should be derived from `QWidget` or something that is derived from `QWidget`.

It must be able to receive mouse down and mouse up events and convert them to pixel coordinates to pass to the parent or a registered handler.

UML of the **full** `ImagePreview` should look something like this:

```mermaid
classDiagram
  class ImagePreview {
    -QPixmap bitmap
    -MainWindow parent
    -QRubberBand|None rubber_band
    -on_mouse_down(QMouseEvent event)
    -on_mouse_up(QMouseEvent event)
    -on_mouse_move(QMouseEvent event)
    +draw_rubber_band_from(tuple~int, int~ start)
    +clear_rubber_band()
    +render_single(ndarray band, int bpp)
    +render_rgb(ndarray rgb_bands, int bpp)
    +render_similar(ndarray band, int bpp, ndarray mask)
  }
```

Remember that the private properties and methods are just a suggestion and the actual implementation may be different.

**Comment by verticalmars** [comment]
from typing import Type, TypeVar, Any, Optional

from PyQt5.QtCore import QObject, QRect, QPoint
from PyQt5.QtGui import QImage, QPixmap, QMouseEvent, QRubberBand
from PyQt5.QtWidgets import QWidget

ScalarType = TypeVar("ScalarType", bound=Any, covariant=True)

class ImagePreview(QWidget):
    def init(self, parent: QWidget, data: Type[ScalarType], bpp: int) -> None:
        super().init(parent)
        self.bitmap = self.render(data, bpp)
        self.parent = parent
        self.rubber_band: Optional[QRubberBand] = None

    def on_mouse_down(self, event: QMouseEvent) -> None:
        self.start = event.pos()
        self.rubber_band = QRubberBand(QRubberBand.Rectangle, self)
        self.rubber_band.setGeometry(QRect(self.start, QSize()))
        self.rubber_band.show()

    def on_mouse_up(self, event: QMouseEvent) -> None:
        self.rubber_band.hide()
        self.parent.on_mouse_up(event.pos())

    def on_mouse_move(self, event: QMouseEvent) -> None:
        self.rubber_band.setGeometry(
            QRect(self.start, event.pos()).normalized()
        )

    def render_single(self, data: Type[ScalarType], bpp: int) -> QPixmap:
        min_val, max_val = data.min(), data.max()
        normalised = (data - min_val) / (max_val - min_val)
        scaled = (normalised * (1 << bpp - 1)).astype("uint8")
        image = QImage(
            scaled.data, scaled.shape[1], scaled.shape[0], scaled.strides[0],
            QImage.Format_Grayscale8,
        )
        return QPixmap.fromImage(image)

    def render_rgb(self, data: Type[ScalarType], bpp: int) -> QPixmap:
        assert data.shape[2] == 3
        min_val, max_val = data.min(), data.max()
        normalised = (data - min_val) / (max_val - min_val)
        scaled = (normalised * (1 << bpp - 1)).astype("uint8")
        image = QImage(
            scaled.data, scaled.shape[1], scaled.shape[0], scaled.strides[0],
            QImage.Format_RGB888,
        )
        return QPixmap.fromImage(image)

    def render_similar(self, data: Type[ScalarType], bpp: int, mask: np.ndarray) -> QPixmap:
        img = self.render_single(data, bpp)
        painter = QPainter()
        painter.begin(img)
        painter.setBr
